// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizFlow.Data;

namespace QuizFlow.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201130173725_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("QuizFlow.Models.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Roundid")
                        .HasColumnType("int");

                    b.Property<string>("answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("points")
                        .HasColumnType("float");

                    b.Property<string>("question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("questionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Roundid");

                    b.HasIndex("userid");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizFlow.Models.Quiz", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("totalPoints")
                        .HasColumnType("float");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizFlow.Models.Round", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Quizid")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("totalPoints")
                        .HasColumnType("float");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Quizid");

                    b.HasIndex("userid");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("QuizFlow.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("passwordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("passwordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuizFlow.Models.Question", b =>
                {
                    b.HasOne("QuizFlow.Models.Round", null)
                        .WithMany("questions")
                        .HasForeignKey("Roundid");

                    b.HasOne("QuizFlow.Models.User", "user")
                        .WithMany("questions")
                        .HasForeignKey("userid");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QuizFlow.Models.Quiz", b =>
                {
                    b.HasOne("QuizFlow.Models.User", "user")
                        .WithMany("quizzes")
                        .HasForeignKey("userid");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QuizFlow.Models.Round", b =>
                {
                    b.HasOne("QuizFlow.Models.Quiz", null)
                        .WithMany("rounds")
                        .HasForeignKey("Quizid");

                    b.HasOne("QuizFlow.Models.User", "user")
                        .WithMany("rounds")
                        .HasForeignKey("userid");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QuizFlow.Models.Quiz", b =>
                {
                    b.Navigation("rounds");
                });

            modelBuilder.Entity("QuizFlow.Models.Round", b =>
                {
                    b.Navigation("questions");
                });

            modelBuilder.Entity("QuizFlow.Models.User", b =>
                {
                    b.Navigation("questions");

                    b.Navigation("quizzes");

                    b.Navigation("rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
